### ISSUE TITLE
ALL ISSUES SHOULD BE SENT TO THE ECJ-INTEREST LIST, NOT HERE.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eclab/ecj#1]
```
See  http://cs.gmu.edu/~eclab/projects/ecj/

Alternatively you can mail Sean Luke directly:   http://cs.gmu.edu/~sean/
```

Original issue reported on code.google.com by `sean.l...@gmail.com` on 18 Feb 2011 at 10:11

**Comment by SigmaX** [comment]
In the future, I hope this policy changes!  GitHub's issue tracker is great, and integrates seamlessly with commit messages.

**Comment by SigmaX** [comment]
This policy may have made sense for Google code -- but GitHub's issue tracker is awesome.  I vote for using both the Listserv and the Issue tracker as complements to each other!

**Comment by SigmaX** [comment]
Closing this, since it was auto-migrated from Google Code, and since we (or at least I) am now actively using the issue manager.
