### ISSUE TITLE
app/gpsemantics prints to STDOUT in silent mode

### ISSUE THREAD

**Issue by SigmaX** [eclab/ecj#20]
The `gpsemantics` app prints some output directly to `stdout` once per run, even when `silent=true`.

This messes things up if we want to collect data directly from `stdout`.

**Comment by eclab** [comment]
GPSemantics were donated problems.  Easily dealt with, replace the lines starting with System.err.println(...) with:

state.output.message("Problem name " + problemName);
state.output.message("Problem size " + problemSize);

Sean
